FROM ft-rails:on-build

EXPOSE 3000
CMD ["rails", "s", "-b", "0.0.0.0", "-p" ,"3000"]

# How to run ?

# build the image with :
# docker build -t ex02img projets/Docker1/01_dockerfiles/ex02/.

# Run the image with :
# docker run ex02img
